version: 2

jobs:
  unitTest:
    docker:
      - image: web3f/node-dind:v0.3.0
      - image: parity/polkadot:v0.8.11 
        name: polkadot
        command: --chain=kusama-dev --ws-port 11000 --alice --ws-external --rpc-methods=Unsafe --rpc-cors=all
    steps:
      - checkout
      - run: yarn
      - run: yarn test

  helmLint:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/polkadot-watcher

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/polkadot-watcher .

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/polkadot-watcher

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unitTest:
          filters:
            tags:
              only: /.*/
      - helmLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTest
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - helmLint
            - unitTest
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - buildImage
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - buildImage
            - integrationTests
